spring:
  datasource:
    url: jdbc:postgresql://gubun-postgre.cbj06ruinatu.us-west-1.rds.amazonaws.com:5432/postgres
    username: gubun_DBA
    password: gt4MW00mv7JSO4EkpXPH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace