spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(Akn44dXsH2btWIRNfqmNJc60LKUOWP2c+PVQ15+xSoZf4ddzGl1JcI13hbWZ9LUVeXo6kwdlBIuw+YKPaSUkK8h0sQWonoADl1lGUFwdS4NAaeQugwBBNJIu6kwxMBJ1)
    username: ENC(EmRRq+Xam8r36WFSPZas2UjrcY/DfwSv)
    password: ENC(daX0fX/g9fgOzXIz8TroQj50f1XwHf4z6qHiPA0Vv3g=)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(7c6ZBBjyz98qhrJ7PrxIuvG2Fm53CSK63ccNRVhaJaM=)
    password: ENC(XOW5B+rJVeeqIc0OL7dJyF9mjCCSBTuWLUyua3WbZa4=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(FkKe3liZ/PpUj3k4iUeQLrS+zejxRelYlygrFbKIH3UTgz6vscqL5MDBWS7t9/Xg)
            client-secret: ENC(iz7RT0THvft9AAZ3p7GZVLecwRuNfkRt1ICycXB9wTuppXTRx7xNlHeYo9cnUWAz)
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

          google:
            client-id: ENC(Atfw7cewc5BN2InmYxrpxaz8Z783VAV65uqZJquyn7MiXTqYRvGne9zdzFY4wWCqE5sqX1sr8szz7DPWJ0BmZ8Cvs7JtZy+YVz4gMy7Eu9VGJvLPVjlqUw==)
            client-secret: ENC(lMkxJ5HbzzASG7SK4Nzj1qm4FlsRzutYwpqz7sE5BCeLQbzRpIF9S0Svln5X+FR2)

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account




cloud:
  aws:
    # s3 bucket 이름 배포시 변경 필요
    s3:
      bucket: ENC(7mulBxQyTXh2O/kWnIUmx01OodzyFZP4)
    # user access-key, secret-key 배포시 작성 필요
    credentials:
      access-key: ENC(yH4Wc9Gokmdtgxema+DSHGFP7dPUjoKV4P0KBgjTZxw=)
      secret-key: ENC(j1lY7VnhJ2TYb885zMnE5OpXZj+X+K3v7YxTMcDgVRgBn4K/whbi5PBbtFAhmS2xT9r3kTtzIHQ=)
    # s3 region
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error # aws meta-data 관련 오류로그 출력x


